server:
  port: 9090

spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#        指定连接池客户端
      client-type: lettuce

      lettuce:
        pool:
        # 连接池最大连接数（使用负值表示没有限制）
          max-active: 10
        # 连接池中的最大空闲连接
          max-idle: 10
        # 连接池中的最小空闲连接
          min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms


      jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 10
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms


  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


  ## 连接池最大连接数（使用负值表示没有限制）
#  spring.redis.lettuce.pool.max-active = 10
#
#  # 连接池中的最大空闲连接
#  spring.redis.lettuce.pool.max-idle = 10
#
#  # 连接池中的最小空闲连接
#  spring.redis.lettuce.pool.min-idle = 0
#
#  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#  spring.redis.lettuce.pool.max-wait= -1ms
#  #指定客户端
#  spring.redis.client-type = lettuce


#数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/video1?serverTimezone=GMT%2b8
    username: root
    password: 1234

logging:
  level:
    net:
      xdclass:
        video:
          conf:
            ProgressWebSocketHandler=DEBUG:
#  mvc:
#    # URL响应地址（Springboot默认为/**)
#    static-path-pattern: /files/**


#    resources:
#      static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources/,file:/files/image/,file:/files/video/
#
#
#
#      profiles:
#    active=dev:
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




chromedriverPath : F:\\chromedriver\\chromedriver.exe
phantomJSDriver :  F:\\phantomjs-2.1.1-windows\\phantomjs-2.1.1-windows\\bin\\phantomjs.exe
